use v6.c;

use GLib::Raw::Definitions;

unit package GStreamer::Raw::PBUtils::Enums;

our enum GstAudioVisualizerShaderEnum is export <
  GST_AUDIO_VISUALIZER_SHADER_NONE
  GST_AUDIO_VISUALIZER_SHADER_FADE
  GST_AUDIO_VISUALIZER_SHADER_FADE_AND_MOVE_UP
  GST_AUDIO_VISUALIZER_SHADER_FADE_AND_MOVE_DOWN
  GST_AUDIO_VISUALIZER_SHADER_FADE_AND_MOVE_LEFT
  GST_AUDIO_VISUALIZER_SHADER_FADE_AND_MOVE_RIGHT
  GST_AUDIO_VISUALIZER_SHADER_FADE_AND_MOVE_HORIZ_OUT
  GST_AUDIO_VISUALIZER_SHADER_FADE_AND_MOVE_HORIZ_IN
  GST_AUDIO_VISUALIZER_SHADER_FADE_AND_MOVE_VERT_OUT
  GST_AUDIO_VISUALIZER_SHADER_FADE_AND_MOVE_VERT_IN
>;

constant GstDiscovererResult is export := guint32;
our enum GstDiscovererResultEnum is export (
  GST_DISCOVERER_OK              => 0,
  GST_DISCOVERER_URI_INVALID     => 1,
  GST_DISCOVERER_ERROR           => 2,
  GST_DISCOVERER_TIMEOUT         => 3,
  GST_DISCOVERER_BUSY            => 4,
  GST_DISCOVERER_MISSING_PLUGINS => 5,
);

constant GstInstallPluginsReturn is export := guint32;
our enum GstInstallPluginsReturnEnum is export (
  GST_INSTALL_PLUGINS_SUCCESS               =>   0,
  GST_INSTALL_PLUGINS_NOT_FOUND             =>   1,
  GST_INSTALL_PLUGINS_ERROR                 =>   2,
  GST_INSTALL_PLUGINS_PARTIAL_SUCCESS       =>   3,
  GST_INSTALL_PLUGINS_USER_ABORT            =>   4,
  GST_INSTALL_PLUGINS_CRASHED               => 100,
  'GST_INSTALL_PLUGINS_INVALID',
  GST_INSTALL_PLUGINS_STARTED_OK            => 200,
  'GST_INSTALL_PLUGINS_INTERNAL_FAILURE',
  'GST_INSTALL_PLUGINS_HELPER_MISSING',
  'GST_INSTALL_PLUGINS_INSTALL_IN_PROGRESS'
);
