/*
  List created from the output of:
    ( find . -name \*.h -exec grep -Hn 'typedef struct' {} \; 1>&2 ) 2>&1 | \
       cut -d\  -f 4 | grep -v \{
*/

/* Strategy provided by p6-XML-LibXML:author<FROGGS> */
#ifdef _WIN32
#define DLLEXPORT __declspec(dllexport)
#else
#define DLLEXPORT extern
#endif

#include <gst/gst.h>
#include <gst/gststreams.h>
#include <gst/gl/gl.h>
#include <gst/gstsample.h>
#include <gst/gsturi.h>
#include <gst/gl/egl/gstgldisplay_egl.h>
#include <gst/gl/wayland/gstgldisplay_wayland.h>
#include <gst/gl/gstglfuncs.h>
#include <gst/gl/x11/gstgldisplay_x11.h>
#include <gst/gl/egl/gstglmemoryegl.h>
#include <gst/gl/egl/gsteglimage.h>
#include <gst/gl/egl/gstglmemoryegl.h>
#include <gst/allocators/gstdmabuf.h>
#include <gst/gl/wayland/gstgldisplay_wayland.h>
#include <gst/audio/audio.h>
#include <gst/check/check.h>
#include <gst/video/video.h>
#include <gst/allocators/allocators.h>
#include <gst/net/net.h>
#include <gst/pbutils/pbutils.h>
#include <gst/rtp/rtp.h>
#include <gst/base/base.h>
#include <gst/riff/riff.h>
#include <gst/rtsp/rtsp.h>
#include <gst/sdp/sdp.h>
#include <gst/tag/tag.h>
#include <gst/app/app.h>
#include <gst/basecamerabinsrc/gstbasecamerasrc.h>
#include <gst/controller/controller.h>
#include <gst/fft/gstfft.h>

#include <gst/interfaces/photography.h>
#include "gst_private.h"

#define s(name)     DLLEXPORT int sizeof_ ## name () { return sizeof(name); }

//s(GstAggregatorPad)
//s(GstAtomicQueue)
//s(GstAudioConverter)
//s(GstAudioStreamAlign)
//s(GstBufferList)
//s(GstBus)
//s(GstCaps)
//s(GstChildProxy)
//s(GstColorBalance)
//s(GstContext)
//s(GstDataQueue)
//s(GstDateTime)
//s(GstDevice)
//s(GstDynamicTypeFactory)
//s(GstElementFactory)
//s(GstEvent)
//s(GstFlowCombiner)
//s(GstGhostPad)
//s(GstParseContext)
//s(GstPipeline)
//s(GstPlugin)
//s(GstPluginFeature)
//s(GstPoll)
//s(GstPreset)
//s(GstProxyPad)
//s(GstQueueArray)
//s(GstRegistry)
//s(GstSample)
//s(GstStream)
//s(GstStreamCollection)
//s(GstTaskPool)
//s(GstToc)
//s(GstTocEntry)
//s(GstTocSetter)
//s(GstTracer)
//s(GstTracerFactory)
//s(GstUri)
//s(GstURIHandler)
//s(GstVideoConverter)
//s(GstVideoDecoder)
//s(GstVideoDither)
//s(GstVideoEncoder)
//s(GstVideoOrientation)
//s(GstVideoScaler)
// s(GstAdapter)
// s(GstAdapterClass)
s(gsize)
s(GstMapFlags)
s(GHookList)
s(GstAggregator)
s(GstAggregatorClass)
s(GstAggregatorPadClass)
s(GstAllocationParams)
// s(GstAllocator)
// s(GstAllocatorClass)
s(GstAppSink)
s(GstAppSinkClass)
s(GstAppSinkCallbacks)
s(GstAppSrc)
s(GstAppSrcClass)
s(GstARGBControlBinding)
s(GstARGBControlBindingClass)
s(GstAudioAggregator)
s(GstAudioAggregatorClass)
s(GstAudioAggregatorConvertPad)
s(GstAudioAggregatorConvertPadClass)
s(GstAudioAggregatorPad)
s(GstAudioAggregatorPadClass)
s(GstAudioBaseSink)
s(GstAudioBaseSinkClass)
s(GstAudioBaseSrc)
s(GstAudioBaseSrcClass)
s(GstAudioCdSrc)
s(GstAudioCdSrcClass)
s(GstAudioCdSrcTrack)
//s(GstAudioChannelMixer)
s(GstAudioClippingMeta)
s(GstAudioClock)
s(GstAudioClockClass)
s(GstAudioDecoder)
s(GstAudioDecoderClass)
s(GstAudioDownmixMeta)
s(GstAudioEncoder)
s(GstAudioEncoderClass)
s(GstAudioFilter)
s(GstAudioFilterClass)
s(GstAudioFormatInfo)
s(GstAudioInfo)
s(GstAudioMeta)
//s(GstAudioQuantize)
//s(GstAudioResampler)
s(GstAudioRingBuffer)
s(GstAudioRingBufferClass)
s(GstAudioRingBufferSpec)
s(GstAudioSink)
s(GstAudioSinkClass)
s(GstAudioSrc)
s(GstAudioSrcClass)
s(GstAudioVisualizer)
s(GstAudioVisualizerClass)
s(GstBaseCameraSrc)
s(GstBaseCameraSrcClass)
s(GstBaseParse)
s(GstBaseParseClass)
s(GstBaseParseFrame)
s(GstBaseSink)
s(GstBaseSinkClass)
s(GstBaseSrc)
s(GstBaseSrcClass)
s(GstBaseTransform)
s(GstBaseTransformClass)
s(GstBin)
s(GstBinClass)
s(GstBitReader)
s(GstBitWriter)
s(GstBuffer)
s(GstBufferPool)
s(GstBufferPoolAcquireParams)
s(GstBufferPoolClass)
s(GstBusClass)
s(GstByteReader)
s(GstByteWriter)
//s(GstCapsFeatures)
//s(GstCheckLogFilter)
s(GstChildProxyInterface)
s(GstClock)
s(GstCollectData)
s(GstCollectPads)
s(GstCollectPadsClass)
s(GstColorBalanceChannel)
s(GstColorBalanceChannelClass)
s(GstColorBalanceInterface)
s(GstControlBinding)
s(GstControlBindingClass)
s(GstControlPoint)
s(GstControlSource)
s(GstControlSourceClass)
s(GstDataQueueClass)
s(GstDataQueueItem)
s(GstDataQueueSize)
s(GstDebugCategory)
//s(GstDebugMessage)
s(GstDeviceClass)
s(GstDeviceMonitor)
s(GstDeviceMonitorClass)
s(GstDeviceProvider)
s(GstDeviceProviderClass)
s(GstDeviceProviderFactory)
s(GstDeviceProviderFactoryClass)
s(GstDirectControlBinding)
s(GstDirectControlBindingClass)
s(GstDiscoverer)
//s(GstDiscovererAudioInfo)
s(GstDiscovererClass)
//s(GstDiscovererContainerInfo)
//s(GstDiscovererInfo)
//s(GstDiscovererStreamInfo)
//s(GstDiscovererSubtitleInfo)
//s(GstDiscovererVideoInfo)
//s(GstDmaBufAllocator)
s(GstDmaBufAllocatorClass)
s(GstDynamicTypeFactoryClass)
s(GstEGLImage)
s(GstElement)
s(GstElementClass)
s(GstElementFactoryClass)
//s(GstEncodingAudioProfile)
//s(GstEncodingAudioProfileClass)
//s(GstEncodingContainerProfile)
//s(GstEncodingContainerProfileClass)
//s(GstEncodingProfile)
//s(GstEncodingProfileClass)
//s(GstEncodingTarget)
//s(GstEncodingVideoProfile)
//s(GstEncodingVideoProfileClass)
s(GstFdAllocator)
s(GstFdAllocatorClass)
// s(GstFFTF32)
// s(GstFFTF32Complex)
// s(GstFFTF64)
// s(GstFFTF64Complex)
// s(GstFFTS16)
// s(GstFFTS16Complex)
// s(GstFFTS32)
// s(GstFFTS32Complex)
s(GstFormatDefinition)
s(GstGhostPadClass)
s(GstGLAllocationParams)
s(GstGLAsyncDebug)
s(GstGLBaseFilter)
s(GstGLBaseFilterClass)
s(GstGLBaseMemory)
s(GstGLBaseMemoryAllocator)
s(GstGLBaseMemoryAllocatorClass)
s(GstGLBuffer)
s(GstGLBufferAllocationParams)
s(GstGLBufferAllocator)
s(GstGLBufferAllocatorClass)
s(GstGLBufferPool)
s(GstGLBufferPoolClass)
s(GstGLColorConvert)
s(GstGLColorConvertClass)
s(GstGLContext)
s(GstGLContextClass)
s(GstGLDisplay)
s(GstGLDisplayClass)
s(GstGLDisplayEGL)
s(GstGLDisplayEGLClass)
s(GstGLDisplayWayland)
s(GstGLDisplayWaylandClass)
s(GstGLDisplayX11)
s(GstGLDisplayX11Class)
s(GstGLFilter)
s(GstGLFilterClass)
s(GstGLFramebuffer)
s(GstGLFramebufferClass)
s(GstGLFuncs)
s(GstGLMemory)
s(GstGLMemoryAllocator)
s(GstGLMemoryAllocatorClass)
s(GstGLMemoryEGL)
//s(GstGLMemoryEGLAllocator)
//s(GstGLMemoryEGLAllocatorClass)
s(GstGLMemoryPBO)
s(GstGLMemoryPBOAllocator)
s(GstGLMemoryPBOAllocatorClass)
s(GstGLOverlayCompositor)
s(GstGLOverlayCompositorClass)
s(GstGLQuery)
s(GstGLRenderbuffer)
s(GstGLRenderbufferAllocationParams)
s(GstGLRenderbufferAllocator)
s(GstGLRenderbufferAllocatorClass)
s(GstGLSyncMeta)
s(GstGLUpload)
s(GstGLUploadClass)
s(GstGLVideoAllocationParams)
s(GstGLViewConvert)
s(GstGLViewConvertClass)
s(GstHarness)
//s(GstHarnessThread)
//s(GstInstallPluginsContext)
s(GstInterpolationControlSource)
s(GstInterpolationControlSourceClass)
s(GstIterator)
s(GstLFOControlSource)
s(GstLFOControlSourceClass)
s(GstMapInfo)
s(GstMemory)
s(GstMessage)
s(GstMeta)
s(GstMetaTransformCopy)
s(GstMetaInfo)
//s(GstMIKEYDecryptInfo)
//s(GstMIKEYEncryptInfo)
s(GstMIKEYMessage)
s(GstMIKEYPayload)
s(GstMiniObject)
//s(GstNavigation)
s(GstNavigationInterface)
s(GstNetAddressMeta)
s(GstNetClientClock)
s(GstNetClientClockClass)
s(GstNetControlMessageMeta)
s(GstNetTimePacket)
s(GstNetTimeProvider)
s(GstNetTimeProviderClass)
s(GstNtpClock)
s(GstNtpClockClass)
s(GstObject)
s(GstObjectClass)
s(GstPad)
s(GstPadClass)
s(GstPadProbeInfo)
s(GstPadTemplate)
s(GstPadTemplateClass)
s(GstParamSpecArray)
s(GstParamSpecFraction)
s(GstParentBufferMeta)
//s(GstPhotography)
//s(GstPhysMemoryAllocator)
s(GstPhysMemoryAllocatorInterface)
s(GstPipelineClass)
s(GstPluginClass)
s(GstPluginDesc)
s(GstPluginFeatureClass)
s(GstPollFD)
s(GstPresetInterface)
s(GstPromise)
s(GstProtectionMeta)
s(GstProxyControlBinding)
s(GstProxyControlBindingClass)
s(GstProxyPadClass)
s(GstPtpClock)
s(GstPtpClockClass)
s(GstPushSrc)
s(GstPushSrcClass)
s(GstQuery)
s(GstReferenceTimestampMeta)
s(GstRegistryClass)
s(GstRTCPBuffer)
s(GstRTCPPacket)
s(GstRTPBaseAudioPayload)
s(GstRTPBaseAudioPayloadClass)
s(GstRTPBaseDepayloadClass)
s(GstRTPBasePayload)
s(GstRTPBasePayloadClass)
s(GstRTPBuffer)
s(GstRTPPayloadInfo)
s(GstRTPSourceMeta)
s(GstRTSPAuthCredential)
s(GstRTSPAuthParam)
//s(GstRTSPConnection)
//s(GstRTSPExtension)
s(GstRTSPExtensionInterface)
s(GstRTSPMessage)
s(GstRTSPRange)
s(GstRTSPTime)
s(GstRTSPTime2)
s(GstRTSPTimeRange)
s(GstRTSPTransport)
s(GstRTSPUrl)
//s(GstRTSPWatch)
s(GstSegment)
s(GstStaticCaps)
s(GstStaticPadTemplate)
s(GstStreamClass)
s(GstStreamCollectionClass)
//s(GstStreamConsistency)
//s(GstStreamVolume)
s(GstStreamVolumeInterface)
s(GstStructure)
s(GstSystemClock)
s(GstSystemClockClass)
s(GstTagList)
s(GstTagMux)
s(GstTagMuxClass)
//s(GstTagXmpWriter)
s(GstTagXmpWriterInterface)
s(GstTask)
s(GstTaskClass)
s(GstTaskPool)
s(GstTaskPoolClass)
// cw: Probably internal test classes
//s(GstTestClock)
//s(GstTestClockClass)
s(GstTimedValue)
s(GstTimedValueControlSource)
s(GstTimedValueControlSourceClass)
s(GstTocSetterInterface)
s(GstTracer)
s(GstTracerClass)
s(GstTracerFactoryClass)
//s(GstTracerRecord)
//s(GstTracerRecordClass)
s(GstTriggerControlSource)
s(GstTriggerControlSourceClass)
s(GstTypeFind)
s(GstTypeFindFactory)
s(GstTypeFindFactoryClass)
s(GstURIHandlerInterface)
//s(GstValueArray)
s(GstValueTable)
s(GstVideoAffineTransformationMeta)
s(GstVideoAggregator)
s(GstVideoAggregatorClass)
s(GstVideoAggregatorConvertPad)
s(GstVideoAggregatorConvertPadClass)
s(GstVideoAggregatorPad)
s(GstVideoAggregatorPadClass)
s(GstVideoAlignment)
s(GstVideoAncillary)
s(GstVideoBufferPool)
s(GstVideoBufferPoolClass)
//s(GstVideoChromaResample)
s(GstVideoCodecFrame)
s(GstVideoCodecState)
s(GstVideoColorimetry)
s(GstVideoCropMeta)
s(GstVideoDecoderClass)
//s(GstVideoDirection)
s(GstVideoDirectionInterface)
s(GstVideoEncoderClass)
s(GstVideoFilter)
s(GstVideoFilterClass)
s(GstVideoFormatInfo)
s(GstVideoFrame)
s(GstVideoGLTextureUploadMeta)
s(GstVideoInfo)
s(GstVideoMeta)
s(GstVideoMetaTransform)
//s(GstVideoMultiviewMeta)
//s(GstVideoMultiviewViewInfo)
s(GstVideoOrientationInterface)
//s(GstVideoOverlay)
s(GstVideoOverlayCompositionMeta)
s(GstVideoOverlayInterface)
s(GstVideoRectangle)
s(GstVideoRegionOfInterestMeta)
s(GstVideoResampler)
s(GstVideoSink)
s(GstVideoSinkClass)
s(GstVideoTimeCode)
s(GstVideoTimeCodeConfig)
s(GstVideoTimeCodeInterval)
s(GstVideoTimeCodeMeta)
//s(GstVideoVBIEncoder)
//s(GstVideoVBIParser)
